import {
  User,
  Post,
  MeetingRequest,
  ActivityLog,
  Interest,
  PlatformStats,
  DashboardStats,
  Notification,
} from "@/types";

const USERS: User[] = [
  {
    id: "u1",
    slug: "john-smith-u1",
    email: "john.smith@stanford.edu",
    firstName: "John",
    lastName: "Smith",
    role: "engineer",
    institution: "Stanford University",
    city: "Palo Alto",
    country: "United States",
    expertise: ["Machine Learning", "Medical Imaging", "Computer Vision"],
    bio: "AI researcher focused on developing diagnostic imaging tools using deep learning.",
    avatarUrl: "",
    profileCompleteness: 95,
    createdAt: "2025-11-15T10:00:00Z",
    isActive: true,
    lastLogin: "2026-04-07T08:00:00Z",
    postCount: 3,
    meetingCount: 5,
    matchRate: 60,
  },
  {
    id: "u2",
    slug: "emily-chen-u2",
    email: "emily.chen@mit.edu",
    firstName: "Emily",
    lastName: "Chen",
    role: "healthcare",
    institution: "MIT Medical",
    city: "Cambridge",
    country: "United States",
    expertise: ["Cardiology", "Clinical Trials", "Telemedicine"],
    bio: "Cardiologist with 10+ years of experience in clinical cardiology and digital health innovation.",
    avatarUrl: "",
    profileCompleteness: 88,
    createdAt: "2025-12-01T14:30:00Z",
    isActive: true,
    lastLogin: "2026-04-06T16:00:00Z",
    postCount: 2,
    meetingCount: 4,
    matchRate: 75,
  },
  {
    id: "u3",
    slug: "sarah-admin-u3",
    email: "admin@healthai.edu",
    firstName: "Sarah",
    lastName: "Admin",
    role: "admin",
    institution: "Health AI Platform",
    city: "Berlin",
    country: "Germany",
    expertise: ["Platform Administration"],
    bio: "Platform administrator.",
    avatarUrl: "",
    profileCompleteness: 100,
    createdAt: "2025-10-01T08:00:00Z",
    isActive: true,
    lastLogin: "2026-04-07T10:00:00Z",
    postCount: 0,
    meetingCount: 0,
    matchRate: 0,
  },
  {
    id: "u4",
    slug: "maria-garcia-u4",
    email: "maria.garcia@charite.edu",
    firstName: "Maria",
    lastName: "Garcia",
    role: "healthcare",
    institution: "Charité – Universitätsmedizin Berlin",
    city: "Berlin",
    country: "Germany",
    expertise: ["Neurology", "Brain Imaging", "EEG Analysis"],
    bio: "Neurologist researching non-invasive brain monitoring for early Alzheimer's detection.",
    avatarUrl: "",
    profileCompleteness: 92,
    createdAt: "2026-01-10T09:00:00Z",
    isActive: true,
    lastLogin: "2026-04-05T14:30:00Z",
    postCount: 1,
    meetingCount: 2,
    matchRate: 50,
  },
  {
    id: "u5",
    slug: "alex-muller-u5",
    email: "alex.mueller@tum.edu",
    firstName: "Alex",
    lastName: "Müller",
    role: "engineer",
    institution: "Technical University of Munich",
    city: "Munich",
    country: "Germany",
    expertise: ["Robotics", "Surgical Systems", "IoT"],
    bio: "Robotics engineer developing next-gen surgical assistance systems.",
    avatarUrl: "",
    profileCompleteness: 78,
    createdAt: "2026-02-05T11:00:00Z",
    isActive: true,
    lastLogin: "2026-04-04T09:00:00Z",
    postCount: 2,
    meetingCount: 1,
    matchRate: 33,
  },
  {
    id: "u6",
    slug: "laura-rossi-u6",
    email: "laura.rossi@polimi.edu",
    firstName: "Laura",
    lastName: "Rossi",
    role: "engineer",
    institution: "Politecnico di Milano",
    city: "Milan",
    country: "Italy",
    expertise: ["Biomedical Engineering", "Wearable Sensors", "Signal Processing"],
    bio: "Biomedical engineer specializing in wearable health monitoring devices.",
    avatarUrl: "",
    profileCompleteness: 85,
    createdAt: "2026-01-20T13:00:00Z",
    isActive: true,
    lastLogin: "2026-04-07T07:00:00Z",
    postCount: 1,
    meetingCount: 3,
    matchRate: 67,
  },
  {
    id: "u7",
    slug: "david-park-u7",
    email: "david.park@kaist.edu",
    firstName: "David",
    lastName: "Park",
    role: "healthcare",
    institution: "KAIST Medical Center",
    city: "Daejeon",
    country: "South Korea",
    expertise: ["Oncology", "Genomics", "Precision Medicine"],
    bio: "Oncologist focused on integrating AI-driven genomics into personalized cancer treatment.",
    avatarUrl: "",
    profileCompleteness: 70,
    createdAt: "2026-03-01T06:00:00Z",
    isActive: false,
    lastLogin: "2026-03-28T12:00:00Z",
    postCount: 1,
    meetingCount: 0,
    matchRate: 0,
  },
];

const POSTS: Post[] = [
  {
    id: "p1",
    authorId: "u1",
    author: USERS[0],
    title: "AI-Powered Cardiac Arrhythmia Detection from ECG Signals",
    domain: "Cardiology Imaging",
    description:
      "Building a deep learning model for real-time ECG arrhythmia classification. Looking for a cardiologist who can provide clinical validation, annotated ECG datasets, and domain expertise on clinically relevant arrhythmia patterns.",
    requiredExpertise: ["Cardiology", "ECG Analysis", "Clinical Validation"],
    projectStage: "prototype",
    commitmentLevel: "medium",
    collaborationType: "research_partner",
    confidentialityLevel: "public",
    city: "Palo Alto",
    country: "United States",
    status: "active",
    expiryDate: "2026-06-01T00:00:00Z",
    autoClose: true,
    createdAt: "2026-03-15T10:00:00Z",
    updatedAt: "2026-03-15T10:00:00Z",
    interestCount: 4,
    highLevelIdea: "Using transformer-based architecture for multi-lead ECG analysis with attention mechanisms.",
  },
  {
    id: "p2",
    authorId: "u2",
    author: USERS[1],
    title: "Digital Twin for Cardiac Rehabilitation Monitoring",
    domain: "Cardiology",
    description:
      "Seeking an engineer to develop a digital twin simulation of cardiac patients undergoing rehabilitation. Need someone with strong ML/simulation background to model patient recovery trajectories.",
    requiredExpertise: ["Machine Learning", "Simulation", "Digital Twin"],
    projectStage: "idea",
    commitmentLevel: "high",
    collaborationType: "co_founder",
    confidentialityLevel: "meeting_only",
    city: "Cambridge",
    country: "United States",
    status: "active",
    expiryDate: "2026-07-15T00:00:00Z",
    autoClose: false,
    createdAt: "2026-03-20T14:00:00Z",
    updatedAt: "2026-03-20T14:00:00Z",
    interestCount: 2,
  },
  {
    id: "p3",
    authorId: "u4",
    author: USERS[3],
    title: "Non-Invasive Brain Monitoring for Alzheimer's Early Detection",
    domain: "Neurology",
    description:
      "Developing a portable EEG-based system for early detection of cognitive decline patterns associated with Alzheimer's. Need signal processing and ML expertise.",
    requiredExpertise: ["Signal Processing", "EEG Analysis", "Machine Learning"],
    projectStage: "concept_validation",
    commitmentLevel: "medium",
    collaborationType: "research_partner",
    confidentialityLevel: "public",
    city: "Berlin",
    country: "Germany",
    status: "meeting_scheduled",
    expiryDate: "2026-08-01T00:00:00Z",
    autoClose: true,
    createdAt: "2026-02-10T09:00:00Z",
    updatedAt: "2026-04-01T11:00:00Z",
    interestCount: 6,
  },
  {
    id: "p4",
    authorId: "u5",
    author: USERS[4],
    title: "Robotic Surgical Assistant for Minimally Invasive Procedures",
    domain: "Surgical Robotics",
    description:
      "Building a next-generation robotic surgical assistant with haptic feedback. Looking for surgeons experienced in minimally invasive procedures to guide design and testing.",
    requiredExpertise: ["Surgery", "Minimally Invasive", "Clinical Testing"],
    projectStage: "prototype",
    commitmentLevel: "high",
    collaborationType: "advisor",
    confidentialityLevel: "meeting_only",
    city: "Munich",
    country: "Germany",
    status: "active",
    expiryDate: "2026-09-01T00:00:00Z",
    autoClose: false,
    createdAt: "2026-03-01T11:00:00Z",
    updatedAt: "2026-03-01T11:00:00Z",
    interestCount: 3,
  },
  {
    id: "p5",
    authorId: "u6",
    author: USERS[5],
    title: "Wearable Continuous Glucose Monitor with Predictive Alerts",
    domain: "Biomedical Engineering",
    description:
      "Developing a non-invasive wearable glucose monitor using photoplethysmography (PPG) signals. Need an endocrinologist to validate measurement accuracy and clinical protocols.",
    requiredExpertise: ["Endocrinology", "Diabetes Management", "Clinical Validation"],
    projectStage: "pilot_testing",
    commitmentLevel: "medium",
    collaborationType: "research_partner",
    confidentialityLevel: "public",
    city: "Milan",
    country: "Italy",
    status: "partner_found",
    expiryDate: "2026-05-01T00:00:00Z",
    autoClose: true,
    createdAt: "2026-01-20T13:00:00Z",
    updatedAt: "2026-03-25T16:00:00Z",
    interestCount: 8,
  },
  {
    id: "p6",
    authorId: "u7",
    author: USERS[6],
    title: "AI Genomics Pipeline for Personalized Cancer Therapy",
    domain: "Oncology",
    description:
      "Looking for a bioinformatics engineer to build an AI pipeline that matches tumor genomic profiles with optimal treatment protocols from clinical literature.",
    requiredExpertise: ["Bioinformatics", "Genomics", "NLP"],
    projectStage: "idea",
    commitmentLevel: "high",
    collaborationType: "co_founder",
    confidentialityLevel: "meeting_only",
    city: "Daejeon",
    country: "South Korea",
    status: "expired",
    expiryDate: "2026-03-01T00:00:00Z",
    autoClose: true,
    createdAt: "2026-01-05T06:00:00Z",
    updatedAt: "2026-03-01T00:00:00Z",
    interestCount: 1,
  },
  {
    id: "p7",
    authorId: "u1",
    author: USERS[0],
    title: "Federated Learning Platform for Multi-Hospital Imaging Data",
    domain: "Medical Imaging",
    description:
      "Building a federated learning framework enabling hospitals to collaboratively train diagnostic imaging models without sharing patient data. Need radiologists for model validation.",
    requiredExpertise: ["Radiology", "Medical Imaging", "Data Privacy"],
    projectStage: "concept_validation",
    commitmentLevel: "low",
    collaborationType: "advisor",
    confidentialityLevel: "public",
    city: "Palo Alto",
    country: "United States",
    status: "active",
    expiryDate: "2026-10-01T00:00:00Z",
    autoClose: false,
    createdAt: "2026-04-01T08:00:00Z",
    updatedAt: "2026-04-01T08:00:00Z",
    interestCount: 0,
  },
  {
    id: "p8",
    authorId: "u5",
    author: USERS[4],
    title: "IoT-Based Patient Vital Signs Monitoring System",
    domain: "IoT Healthcare",
    description:
      "Developing an IoT ecosystem for real-time patient monitoring in hospital wards. Seeking clinical partner for workflow integration and alarm threshold optimization.",
    requiredExpertise: ["Critical Care", "Patient Monitoring", "Clinical Workflows"],
    projectStage: "prototype",
    commitmentLevel: "medium",
    collaborationType: "research_partner",
    confidentialityLevel: "public",
    city: "Munich",
    country: "Germany",
    status: "draft",
    expiryDate: "2026-08-15T00:00:00Z",
    autoClose: true,
    createdAt: "2026-04-05T15:00:00Z",
    updatedAt: "2026-04-05T15:00:00Z",
    interestCount: 0,
  },
];

const INTERESTS: Interest[] = [
  {
    id: "i1",
    postId: "p1",
    userId: "u2",
    user: USERS[1],
    message: "I have extensive experience with ECG interpretation and arrhythmia classification. Would love to discuss potential collaboration on ground truth labeling.",
    createdAt: "2026-03-18T09:00:00Z",
  },
  {
    id: "i2",
    postId: "p1",
    userId: "u4",
    user: USERS[3],
    message: "Although neurology is my primary field, I have cross-functional experience in cardiac electrophysiology. Interested in discussing.",
    createdAt: "2026-03-19T14:00:00Z",
  },
  {
    id: "i3",
    postId: "p3",
    userId: "u6",
    user: USERS[5],
    message: "My wearable sensor background in signal processing could directly apply to portable EEG development. Very interested!",
    createdAt: "2026-02-15T10:00:00Z",
  },
  {
    id: "i4",
    postId: "p4",
    userId: "u2",
    user: USERS[1],
    message: "I work closely with our surgical team and can connect you with minimally invasive procedure specialists.",
    createdAt: "2026-03-10T16:30:00Z",
  },
];

const MEETINGS: MeetingRequest[] = [
  {
    id: "m1",
    postId: "p1",
    post: POSTS[0],
    requesterId: "u2",
    requester: USERS[1],
    receiverId: "u1",
    receiver: USERS[0],
    message: "Would love to discuss the ECG arrhythmia detection project. I can provide clinical validation expertise.",
    proposedSlots: [
      { id: "ts1", date: "2026-04-15", startTime: "10:00", endTime: "11:00" },
      { id: "ts2", date: "2026-04-16", startTime: "14:00", endTime: "15:00" },
      { id: "ts3", date: "2026-04-17", startTime: "09:00", endTime: "10:00" },
    ],
    selectedSlot: { id: "ts2", date: "2026-04-16", startTime: "14:00", endTime: "15:00" },
    status: "scheduled",
    ndaAccepted: true,
    meetingLink: "https://zoom.us/j/mock-meeting-1",
    createdAt: "2026-04-01T10:00:00Z",
    updatedAt: "2026-04-03T14:00:00Z",
  },
  {
    id: "m2",
    postId: "p3",
    post: POSTS[2],
    requesterId: "u6",
    requester: USERS[5],
    receiverId: "u4",
    receiver: USERS[3],
    message: "My signal processing expertise aligns perfectly with your EEG project. Let's connect!",
    proposedSlots: [
      { id: "ts4", date: "2026-04-20", startTime: "11:00", endTime: "12:00" },
      { id: "ts5", date: "2026-04-21", startTime: "15:00", endTime: "16:00" },
    ],
    status: "pending",
    ndaAccepted: true,
    createdAt: "2026-04-05T08:00:00Z",
    updatedAt: "2026-04-05T08:00:00Z",
  },
  {
    id: "m3",
    postId: "p4",
    post: POSTS[3],
    requesterId: "u2",
    requester: USERS[1],
    receiverId: "u5",
    receiver: USERS[4],
    message: "I can connect you with experienced surgeons for clinical testing of the robotic assistant.",
    proposedSlots: [
      { id: "ts6", date: "2026-04-10", startTime: "09:00", endTime: "10:00" },
    ],
    selectedSlot: { id: "ts6", date: "2026-04-10", startTime: "09:00", endTime: "10:00" },
    status: "completed",
    ndaAccepted: true,
    createdAt: "2026-03-20T12:00:00Z",
    updatedAt: "2026-04-10T10:00:00Z",
  },
  {
    id: "m4",
    postId: "p2",
    post: POSTS[1],
    requesterId: "u1",
    requester: USERS[0],
    receiverId: "u2",
    receiver: USERS[1],
    message: "The digital twin concept for cardiac rehab is fascinating. I have ML/simulation experience to discuss.",
    proposedSlots: [
      { id: "ts7", date: "2026-04-22", startTime: "13:00", endTime: "14:00" },
      { id: "ts8", date: "2026-04-23", startTime: "10:00", endTime: "11:00" },
    ],
    status: "declined",
    ndaAccepted: true,
    createdAt: "2026-04-02T16:00:00Z",
    updatedAt: "2026-04-04T09:00:00Z",
  },
  {
    id: "m5",
    postId: "p5",
    post: POSTS[4],
    requesterId: "u1",
    requester: USERS[0],
    receiverId: "u6",
    receiver: USERS[5],
    message: "I am interested in the predictive validation part of your glucose monitor.",
    proposedSlots: [
      { id: "ts9", date: "2026-04-18", startTime: "16:00", endTime: "17:00" },
    ],
    selectedSlot: { id: "ts9", date: "2026-04-18", startTime: "16:00", endTime: "17:00" },
    status: "scheduled",
    ndaAccepted: true,
    meetingLink: "https://teams.microsoft.com/mock-meeting-5",
    createdAt: "2026-04-06T11:00:00Z",
    updatedAt: "2026-04-07T09:00:00Z",
  },
  {
    id: "m6",
    postId: "p8",
    post: POSTS[7],
    requesterId: "u2",
    requester: USERS[1],
    receiverId: "u5",
    receiver: USERS[4],
    message: "Clinicalpartner discussion regarding vital signs monitoring.",
    proposedSlots: [
      { id: "ts10", date: "2026-04-25", startTime: "14:00", endTime: "15:00" },
    ],
    status: "pending",
    ndaAccepted: true,
    createdAt: "2026-04-07T13:00:00Z",
    updatedAt: "2026-04-07T13:00:00Z",
  },
];

const LOGS: ActivityLog[] = [
  { id: "l1", userId: "u1", userName: "John Smith", userRole: "engineer", actionType: "login", targetEntity: "session", targetId: "s1", resultStatus: "success", timestamp: "2026-04-07T08:00:00Z", ipAddress: "192.168.1.10" },
  { id: "l2", userId: "u2", userName: "Emily Chen", userRole: "healthcare", actionType: "login", targetEntity: "session", targetId: "s2", resultStatus: "success", timestamp: "2026-04-06T16:00:00Z", ipAddress: "10.0.0.15" },
  { id: "l3", userId: "u1", userName: "John Smith", userRole: "engineer", actionType: "post_create", targetEntity: "post", targetId: "p7", resultStatus: "success", timestamp: "2026-04-01T08:00:00Z", ipAddress: "192.168.1.10" },
  { id: "l4", userId: "u6", userName: "Laura Rossi", userRole: "engineer", actionType: "meeting_request", targetEntity: "meeting", targetId: "m2", resultStatus: "success", timestamp: "2026-04-05T08:00:00Z", ipAddress: "172.16.0.5" },
  { id: "l5", userId: "u2", userName: "Emily Chen", userRole: "healthcare", actionType: "interest_express", targetEntity: "post", targetId: "p4", resultStatus: "success", timestamp: "2026-03-10T16:30:00Z", ipAddress: "10.0.0.15" },
  { id: "l6", userId: "u5", userName: "Alex Müller", userRole: "engineer", actionType: "post_create", targetEntity: "post", targetId: "p8", resultStatus: "success", timestamp: "2026-04-05T15:00:00Z", ipAddress: "192.168.5.20" },
  { id: "l7", userId: "u4", userName: "Maria Garcia", userRole: "healthcare", actionType: "post_edit", targetEntity: "post", targetId: "p3", resultStatus: "success", timestamp: "2026-04-01T11:00:00Z", ipAddress: "10.10.0.8" },
  { id: "l8", userId: "u3", userName: "Sarah Admin", userRole: "admin", actionType: "user_suspend", targetEntity: "user", targetId: "u7", resultStatus: "success", timestamp: "2026-04-03T10:00:00Z", ipAddress: "172.20.0.1" },
  { id: "l9", userId: "unknown", userName: "Unknown", userRole: "engineer", actionType: "login", targetEntity: "session", targetId: "s_fail", resultStatus: "failure", timestamp: "2026-04-06T03:00:00Z", ipAddress: "203.0.113.50" },
  { id: "l10", userId: "u6", userName: "Laura Rossi", userRole: "engineer", actionType: "post_close", targetEntity: "post", targetId: "p5", resultStatus: "success", timestamp: "2026-03-25T16:00:00Z", ipAddress: "172.16.0.5" },
  { id: "l11", userId: "u1", userName: "John Smith", userRole: "engineer", actionType: "meeting_accept", targetEntity: "meeting", targetId: "m1", resultStatus: "success", timestamp: "2026-04-03T14:00:00Z", ipAddress: "192.168.1.10" },
  { id: "l12", userId: "u2", userName: "Emily Chen", userRole: "healthcare", actionType: "meeting_decline", targetEntity: "meeting", targetId: "m4", resultStatus: "success", timestamp: "2026-04-04T09:00:00Z", ipAddress: "10.0.0.15" },
];

const NOTIFICATIONS: Notification[] = [
  { id: "n1", type: "interest", message: "Emily Chen expressed interest in your ECG project", read: false, createdAt: "2026-04-06T16:00:00Z", linkTo: "/dashboard/post/p1" },
  { id: "n2", type: "meeting_request", message: "Laura Rossi sent a meeting request for the EEG project", read: false, createdAt: "2026-04-05T08:00:00Z", linkTo: "/dashboard/meetings" },
  { id: "n3", type: "meeting_accepted", message: "Your meeting with John Smith has been scheduled", read: true, createdAt: "2026-04-03T14:00:00Z", linkTo: "/dashboard/meetings" },
  { id: "n4", type: "partner_found", message: "Laura Rossi marked 'Wearable Glucose Monitor' as Partner Found!", read: true, createdAt: "2026-03-25T16:00:00Z", linkTo: "/dashboard/post/p5" },
];

const PLATFORM_STATS: PlatformStats = {
  totalUsers: 156,
  totalPosts: 89,
  activePosts: 34,
  totalMeetings: 67,
  matchRate: 42,
  weeklyRegistrations: [
    { week: "W1 Mar", count: 8 },
    { week: "W2 Mar", count: 12 },
    { week: "W3 Mar", count: 15 },
    { week: "W4 Mar", count: 10 },
    { week: "W1 Apr", count: 18 },
    { week: "W2 Apr", count: 22 },
  ],
  roleDistribution: [
    { role: "Engineer", count: 89 },
    { role: "Healthcare", count: 62 },
    { role: "Admin", count: 5 },
  ],
  domainDistribution: [
    { domain: "Cardiology", count: 18 },
    { domain: "Neurology", count: 14 },
    { domain: "Medical Imaging", count: 22 },
    { domain: "Surgical Robotics", count: 8 },
    { domain: "Biomedical Eng.", count: 12 },
    { domain: "Oncology", count: 9 },
    { domain: "IoT Healthcare", count: 6 },
  ],
  statusDistribution: [
    { status: "Active", count: 34 },
    { status: "Draft", count: 12 },
    { status: "Meeting Scheduled", count: 15 },
    { status: "Partner Found", count: 18 },
    { status: "Expired", count: 10 },
  ],
};

const DASHBOARD_STATS: DashboardStats = {
  activePosts: 3,
  pendingMeetings: 2,
  totalMatches: 1,
  profileViews: 47,
};

export {
  USERS,
  POSTS,
  INTERESTS,
  MEETINGS,
  LOGS,
  NOTIFICATIONS,
  PLATFORM_STATS,
  DASHBOARD_STATS,
};
